# Generated by Django 6.0.3 on 2026-08-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_donation_options_alter_donation_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('artisan', 'Artisan / Kumhar Samaj'), ('youth', 'Youth / Skill Development'), ('startup', 'Startup / Business'), ('scholarship', 'Scholarship / Education')], db_index=True, max_length=20)),
                ('department', models.CharField(blank=True, default='', max_length=200)),
                ('short_description', models.TextField()),
                ('eligibility', models.TextField(blank=True, default='')),
                ('benefits', models.TextField(blank=True, default='')),
                ('official_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number shows first')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchemeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source_link', models.URLField(max_length=800, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('published_date', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
